### GET HelloWorld
GET http://localhost:3000/
Accept: application/json

### POST Public Auth
POST http://localhost:3000/public/auth
Content-Type: application/json

{}

### POST Private Auth
POST http://localhost:3000/private/auth
Content-Type: application/json

{}


### POST Private msg
POST http://localhost:3000/private/msg
Content-Type: application/json

{
  "msg": "msg"
}

### GET Public msg
GET http://localhost:3000/public/msg?token=c94a8380-010a-4e84-b75d-6b9269dca4a9
Accept: application/json
